# Production Configuration for Cosmic Gardener Backend

# Basic settings (override with environment variables)
database_url = "postgresql://prod:prod@localhost:5432/cosmic_gardener_prod"
jwt_secret = "CHANGE_THIS_TO_SECURE_SECRET_IN_PRODUCTION"
server_host = "0.0.0.0"
server_port = 8080
cors_allowed_origins = ["https://your-frontend-domain.com"]

# Redis settings
redis_url = "redis://localhost:6379"
redis_pool_size = 20
cache_enabled = true

# Metrics settings
metrics_enabled = true
metrics_namespace = "cosmic_gardener_prod"
metrics_endpoint = "/metrics"

# Detailed component configurations
[metrics]
enabled = true
namespace = "cosmic_gardener_prod"
endpoint = "/metrics"
export_interval_seconds = 30

[cache]
player_state_ttl_seconds = 1800
user_session_ttl_seconds = 3600
celestial_bodies_ttl_seconds = 900
game_stats_ttl_seconds = 60
leaderboard_ttl_seconds = 300

[database_pool]
max_size = 20
min_idle = 5
max_lifetime_seconds = 3600
idle_timeout_seconds = 300
connection_timeout_seconds = 10

[database_pool.timeouts]
wait_for_connection_secs = 10
create_connection_secs = 10
recycle_connection_secs = 10

[logging]
level = "info"
format = "Json"
enable_json = true
enable_file_logging = true
file_path = "logs/cosmic-gardener-prod.log"
max_file_size_mb = 500
max_files = 50

[compression]
algorithm = "Lz4"
min_size_threshold = 100
enable_adaptive = true
max_compression_ratio = 0.7
adaptive_threshold_bytes = 2048

[physics]
simd_threshold = 16
direct_threshold = 128
gravitational_constant = 6.67430e-11
softening_factor = 1e-6
max_velocity = 29979245.8

[game_loop]
target_tps = 60
max_celestial_bodies = 5000
cleanup_interval_seconds = 180
metrics_interval_seconds = 30